language: python
python:
- 3.6
dist: trusty
addons:
  apt:
    packages:
    - jq
    - moreutils
    - gettext
install:
- pip install -r requirements-dev.txt
script:
- set -eo pipefail
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: master
env:
  global:
  - secure: NCI3FJh0VX5QrzgbUiKee0ax2DzMf+1u2djxXdm4CYf1FFkQcqENYWqK7sqr6D0uafRkh0E/638mD+gtFkxMBGKAJQHiyyea6CsI3OPPz3sUhIz+xTg5MkUCXhZB8HjjWqov5+/WPxB0tssdWq3v3l9AzT3kS7ASgVSoLg+DRCJ1VeW9lt6WO5QnuDcIRVx3QoXPaEfigINmBeB3ZCUOX2PaDNO627X7OgI3KfGlbg4lmNPjGzeDxWHr3mMjPErR9EDZRWqEXrutVU95oy9Ap0Y2ilbMR+0JUleRLI5HZtRU7bFwBJ6a6i2Y1QlyGOWC3AUdm6Cx9Ic8KmcxkiyLYw68fCt8H2ZlWAxL/fueMG5WkvDowUZndSUCBf4j/eDgpSRUEA+QitkFzU4k6bg9a2KRKWZRHLUd2eX7+ydcf43uIylu2cutOXoqCCoozprmqn57gg1CNCnbUEydw1vmjTR9UFtyqDP+Y0T+1n0A24aZdlgVZxjzkdPinHtlDMjaJX90Qu5ITAH3LZ82fL37e6OYCNyZkLJRkH6ucHSNTvoVe8M3i3zKcqfjrvGmoLRCon64n4SZ1BReuz4i697E61Js2Tn21jaTXMhE/7nMh0Cu1KX+X9GaC7aNoZOw74Ue69ai2CtsYBSc+ACBh3kTono7vm1CjMsZVa6u+axedo8=
  - secure: FrclDg8BxaVkA85XYhOIpkqWLGWbLkTWuMN7CuWYaNxQcoJ6kzGSbQ0PbmTElAMvkVwocNVtQMsQ8d9Ki/VU34DidGInHoahu4bAmSL7b4zlO8G3kGFPTSUJz4XUub1n/p9F27sjyn3myGCTCtnBt3uAluJCvG+bQzHDYcTpb6G68yhdgAm9uWBmwOAefsIAlP7Ll6ZM2aAOZuPkFmpJHqAieOiWiWf0HZpevJvBH8KVV747O663KxmoCsKmvgIhd2bz2/Aa4YDjMiSWayuFmdaTCjgZkF4VaN98r2/l5m9bkKFyDBvfEwmGFRWHV88PrKaAPmRkFibBEXQ8NLcLk9afyEUnY0/8JD90MvXG+bQkegNVeSdzcFTeN+Jd2FvKI0+XEVvAXCndBR0FhyGnP2XPTIdWdzNq3rrxMuXfM8MGMHhKmUxwCn57n0mWBPFt+E4JaaSmrj5jQPS4MBlqgxPE2udDEANZ8TPVLK627lDFMgg/8vemRKphYwZoIyIV/pe8fQ6k1xfjhUz4Zn1wYH3ftfHqTG6mZY3hijBWEk22xWrJTiu4+on+1pNNjeJ9wK+/uwmgpB3yqg1PiWHPUxpdyrdvTq3EPVrIA6iZLYA9nTcnVcnFBZFFv5iuMK6PYPE/SkNoOQQbstkBs2EGadAExNU1G6RvbKw3Tj4LtcE=
